# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ConnectDBDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_connectdbDialog(object):
    def setupUi(self, connectdbDialog):
        connectdbDialog.setObjectName("connectdbDialog")
        connectdbDialog.resize(286, 429)
        self.connectdbBox = QtWidgets.QDialogButtonBox(connectdbDialog)
        self.connectdbBox.setGeometry(QtCore.QRect(40, 370, 181, 32))
        self.connectdbBox.setOrientation(QtCore.Qt.Horizontal)
        self.connectdbBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.connectdbBox.setObjectName("connectdbBox")
        self.label_6 = QtWidgets.QLabel(connectdbDialog)
        self.label_6.setGeometry(QtCore.QRect(50, 220, 54, 12))
        self.label_6.setObjectName("label_6")
        self.cdbDBlineEdit = QtWidgets.QLineEdit(connectdbDialog)
        self.cdbDBlineEdit.setGeometry(QtCore.QRect(130, 210, 113, 20))
        self.cdbDBlineEdit.setObjectName("cdbDBlineEdit")
        self.label_2 = QtWidgets.QLabel(connectdbDialog)
        self.label_2.setGeometry(QtCore.QRect(50, 120, 54, 12))
        self.label_2.setObjectName("label_2")
        self.label_5 = QtWidgets.QLabel(connectdbDialog)
        self.label_5.setGeometry(QtCore.QRect(50, 310, 54, 12))
        self.label_5.setObjectName("label_5")
        self.cdbPortlineEdit = QtWidgets.QLineEdit(connectdbDialog)
        self.cdbPortlineEdit.setGeometry(QtCore.QRect(130, 170, 113, 20))
        self.cdbPortlineEdit.setObjectName("cdbPortlineEdit")
        self.cdbNamelineEdit = QtWidgets.QLineEdit(connectdbDialog)
        self.cdbNamelineEdit.setGeometry(QtCore.QRect(130, 70, 113, 20))
        self.cdbNamelineEdit.setObjectName("cdbNamelineEdit")
        self.cdbHostlineEdit = QtWidgets.QLineEdit(connectdbDialog)
        self.cdbHostlineEdit.setGeometry(QtCore.QRect(130, 120, 113, 20))
        self.cdbHostlineEdit.setObjectName("cdbHostlineEdit")
        self.label = QtWidgets.QLabel(connectdbDialog)
        self.label.setGeometry(QtCore.QRect(50, 70, 54, 12))
        self.label.setObjectName("label")
        self.label_3 = QtWidgets.QLabel(connectdbDialog)
        self.label_3.setGeometry(QtCore.QRect(50, 250, 54, 12))
        self.label_3.setObjectName("label_3")
        self.cdbUserNamelineEdit = QtWidgets.QLineEdit(connectdbDialog)
        self.cdbUserNamelineEdit.setGeometry(QtCore.QRect(130, 250, 113, 20))
        self.cdbUserNamelineEdit.setObjectName("cdbUserNamelineEdit")
        self.label_4 = QtWidgets.QLabel(connectdbDialog)
        self.label_4.setGeometry(QtCore.QRect(50, 170, 54, 12))
        self.label_4.setObjectName("label_4")
        self.cdbPWDlineEdit = QtWidgets.QLineEdit(connectdbDialog)
        self.cdbPWDlineEdit.setGeometry(QtCore.QRect(130, 300, 113, 20))
        self.cdbPWDlineEdit.setObjectName("cdbPWDlineEdit")

        self.retranslateUi(connectdbDialog)
        # self.connectdbBox.accepted.connect(connectdbDialog.accept)
        # self.connectdbBox.rejected.connect(connectdbDialog.reject)
        # QtCore.QMetaObject.connectSlotsByName(connectdbDialog)

    def retranslateUi(self, connectdbDialog):
        _translate = QtCore.QCoreApplication.translate
        connectdbDialog.setWindowTitle(_translate("connectdbDialog", "Connect DB"))
        self.label_6.setText(_translate("connectdbDialog", "Database"))
        self.label_2.setText(_translate("connectdbDialog", "Host"))
        self.label_5.setText(_translate("connectdbDialog", "Password"))
        self.label.setText(_translate("connectdbDialog", "Name"))
        self.label_3.setText(_translate("connectdbDialog", "User name"))
        self.label_4.setText(_translate("connectdbDialog", "Port"))
