# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'NewDBDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_newdbDialog(object):
    def setupUi(self, newdbDialog):
        newdbDialog.setObjectName("newdbDialog")
        newdbDialog.resize(336, 425)
        self.newdbBox = QtWidgets.QDialogButtonBox(newdbDialog)
        self.newdbBox.setGeometry(QtCore.QRect(70, 380, 171, 32))
        self.newdbBox.setOrientation(QtCore.Qt.Horizontal)
        self.newdbBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.newdbBox.setObjectName("newdbBox")
        self.ndbNamelineEdit = QtWidgets.QLineEdit(newdbDialog)
        self.ndbNamelineEdit.setGeometry(QtCore.QRect(170, 70, 113, 20))
        self.ndbNamelineEdit.setObjectName("ndbNamelineEdit")
        self.ndbHostlineEdit = QtWidgets.QLineEdit(newdbDialog)
        self.ndbHostlineEdit.setGeometry(QtCore.QRect(170, 120, 113, 20))
        self.ndbHostlineEdit.setObjectName("ndbHostlineEdit")
        self.ndbPortlineEdit = QtWidgets.QLineEdit(newdbDialog)
        self.ndbPortlineEdit.setGeometry(QtCore.QRect(170, 170, 113, 20))
        self.ndbPortlineEdit.setObjectName("ndbPortlineEdit")
        self.ndbUserNamelineEdit = QtWidgets.QLineEdit(newdbDialog)
        self.ndbUserNamelineEdit.setGeometry(QtCore.QRect(170, 250, 113, 20))
        self.ndbUserNamelineEdit.setObjectName("ndbUserNamelineEdit")
        self.ndbPWDlineEdit = QtWidgets.QLineEdit(newdbDialog)
        self.ndbPWDlineEdit.setGeometry(QtCore.QRect(170, 300, 113, 20))
        self.ndbPWDlineEdit.setObjectName("ndbPWDlineEdit")
        self.label = QtWidgets.QLabel(newdbDialog)
        self.label.setGeometry(QtCore.QRect(90, 70, 54, 12))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(newdbDialog)
        self.label_2.setGeometry(QtCore.QRect(90, 120, 54, 12))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(newdbDialog)
        self.label_3.setGeometry(QtCore.QRect(90, 250, 54, 12))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(newdbDialog)
        self.label_4.setGeometry(QtCore.QRect(90, 170, 54, 12))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(newdbDialog)
        self.label_5.setGeometry(QtCore.QRect(90, 310, 54, 12))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(newdbDialog)
        self.label_6.setGeometry(QtCore.QRect(90, 220, 54, 12))
        self.label_6.setObjectName("label_6")
        self.ndbDBlineEdit = QtWidgets.QLineEdit(newdbDialog)
        self.ndbDBlineEdit.setGeometry(QtCore.QRect(170, 210, 113, 20))
        self.ndbDBlineEdit.setObjectName("ndbDBlineEdit")

        self.retranslateUi(newdbDialog)
        # self.newdbBox.accepted.connect(newdbDialog.accept)
        # self.newdbBox.rejected.connect(newdbDialog.reject)
        # QtCore.QMetaObject.connectSlotsByName(newdbDialog)

    def retranslateUi(self, newdbDialog):
        _translate = QtCore.QCoreApplication.translate
        newdbDialog.setWindowTitle(_translate("newdbDialog", "New DB"))
        self.label.setText(_translate("newdbDialog", "Name"))
        self.label_2.setText(_translate("newdbDialog", "Host"))
        self.label_3.setText(_translate("newdbDialog", "User name"))
        self.label_4.setText(_translate("newdbDialog", "Port"))
        self.label_5.setText(_translate("newdbDialog", "Password"))
        self.label_6.setText(_translate("newdbDialog", "Database"))
